### ISSUE TITLE
[install] macbook12-spi-driver-dkms fails to install

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#644]
This is the error from a recent GitHub Actions workflow. This appears to be due to a hard-coded assumption of what the package version is. The AUR package was updated recently (to support Linux 6.4).

```
+/workdir/scripts/winesapos-install.sh:931> yay_install_chroot macbook12-spi-driver-dkms
+yay_install_chroot:1> chroot /winesapos sudo -u winesap yay --noconfirm -S --removemake macbook12-spi-driver-dkms
Sync Explicit (1): macbook12-spi-driver-dkms-0+git.314-2
resolving dependencies...
looking for conflicting packages...

Package (1)                                  New Version  Net Change  Download Size

winesapos-testing/macbook12-spi-driver-dkms  0+git.314-2    0.17 MiB       0.05 MiB

Total Download Size:   0.05 MiB
Total Installed Size:  0.17 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
--2023-08-20 04:24:37--  https://winesapos.lukeshort.cloud/repo/winesapos-testing/x86_64/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving winesapos.lukeshort.cloud (winesapos.lukeshort.cloud)... 207.244.227.218
Connecting to winesapos.lukeshort.cloud (winesapos.lukeshort.cloud)|207.244.227.218|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57107 (56K) [application/octet-stream]
Saving to: ‘/var/cache/pacman/pkg/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst.part’

     0K .......... .......... .......... .......... .......... 89%  449K 0s
    50K .....                                                 100% 23.2M=0.1s

2023-08-20 04:24:37 (500 KB/s) - ‘/var/cache/pacman/pkg/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst.part’ saved [57107/57107]

checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing macbook12-spi-driver-dkms...
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Install DKMS modules
==> dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 5.15.126-1-lts515
Error! Bad return status for module build on kernel: 5.15.126-1-lts515 (x86_64)
Consult /var/lib/dkms/macbook12-spi-driver/0+git.314/build/make.log for more information.
==> WARNING: `dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 5.15.126-1-lts515' exited 10
==> dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 6.1.46-1-lts
Error! Bad return status for module build on kernel: 6.1.46-1-lts (x86_64)
Consult /var/lib/dkms/macbook12-spi-driver/0+git.314/build/make.log for more information.
==> WARNING: `dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 6.1.46-1-lts' exited 10
(3/3) Refreshing PackageKit...
Error connecting: Could not connect: No such file or directory
error: command failed to execute correctly
+yay_install_chroot:2> clear_cache
+clear_cache:1> chroot /winesapos pacman --noconfirm -S -c -c

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] 

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
+clear_cache:4> rm -rf /winesapos/var/cache/pacman/pkg/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst
clear_cache:5: no matches found: /winesapos/home/winesap/.cache/go-build/*
clear_cache:6: no matches found: /winesapos/home/winesap/.cache/paru/*
+clear_cache:7> rm -rf /winesapos/home/winesap/.cache/yay/completion.cache
clear_cache:8: no matches found: /winesapos/home/winesap/.cargo/*
clear_cache:9: no matches found: /winesapos/tmp/*
+/workdir/scripts/winesapos-install.sh:934> kernel_ver_lts_latest=+/workdir/scripts/winesapos-install.sh:934> grep 5.15
+/workdir/scripts/winesapos-install.sh:934> kernel_ver_lts_latest=+/workdir/scripts/winesapos-install.sh:934> kernel_ver_lts_latest=+/workdir/scripts/winesapos-install.sh:934> ls -1 /winesapos/usr/lib/modules/
+/workdir/scripts/winesapos-install.sh:934> grep -v extramodules
+/workdir/scripts/winesapos-install.sh:934> kernel_ver_lts_latest=+/workdir/scripts/winesapos-install.sh:934> tail -n 1
+/workdir/scripts/winesapos-install.sh:934> kernel_ver_lts_latest=5.15.126-1-lts515 
+/workdir/scripts/winesapos-install.sh:935> chroot /winesapos dkms install --no-depmod macbook12-spi-driver/0+git.304 -k 5.15.126-1-lts515 --force
Sign command: /usr/lib/modules/5.15.126-1-lts515/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Error! Could not find module source directory.
Directory: /usr/src/macbook12-spi-driver-0+git.304 does not exist.
```

https://github.com/LukeShortCloud/winesapOS/actions/runs/5915199279/job/16041220955

**Comment by LukeShortCloud** [comment]
I fixed the issue with the driver version being hard-coded. Now it's dynamic. Upgrades work but the install does not. Here's the latest error which looks similar but the dynamic code does fix a silent/unrelated issue.

```
+yay_install_chroot:1> chroot /winesapos sudo -u winesap yay --noconfirm -S --removemake macbook12-spi-driver-dkms
Sync Explicit (1): macbook12-spi-driver-dkms-0+git.314-2
resolving dependencies...
looking for conflicting packages...

Package (1)                                  New Version  Net Change  Download Size

winesapos-testing/macbook12-spi-driver-dkms  0+git.314-2    0.17 MiB       0.05 MiB

Total Download Size:   0.05 MiB
Total Installed Size:  0.17 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
--2023-08-20 06:03:21--  https://winesapos.lukeshort.cloud/repo/winesapos-testing/x86_64/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving winesapos.lukeshort.cloud (winesapos.lukeshort.cloud)... 207.244.227.218
Connecting to winesapos.lukeshort.cloud (winesapos.lukeshort.cloud)|207.244.227.218|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57107 (56K) [application/octet-stream]
Saving to: ‘/var/cache/pacman/pkg/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst.part’

     0K .......... .......... .......... .......... .......... 89%  438K 0s
    50K .....                                                 100% 15.8M=0.1s

2023-08-20 06:03:22 (487 KB/s) - ‘/var/cache/pacman/pkg/macbook12-spi-driver-dkms-0+git.314-2-x86_64.pkg.tar.zst.part’ saved [57107/57107]

checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing macbook12-spi-driver-dkms...
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Install DKMS modules
==> dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 5.15.126-1-lts515
Error! Bad return status for module build on kernel: 5.15.126-1-lts515 (x86_64)
Consult /var/lib/dkms/macbook12-spi-driver/0+git.314/build/make.log for more information.
==> WARNING: `dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 5.15.126-1-lts515' exited 10
==> dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 6.1.46-1-lts
Error! Bad return status for module build on kernel: 6.1.46-1-lts (x86_64)
Consult /var/lib/dkms/macbook12-spi-driver/0+git.314/build/make.log for more information.
==> WARNING: `dkms install --no-depmod macbook12-spi-driver/0+git.314 -k 6.1.46-1-lts' exited 10
(3/3) Refreshing PackageKit...
Error connecting: Could not connect: No such file or directory
error: command failed to execute correctly
```

https://github.com/LukeShortCloud/winesapOS/actions/runs/5915575767/job/16041974673

**Comment by LukeShortCloud** [comment]
I'm getting the same error as reported on the AUR package that is supposed to be fixed by the latest PKGBUILD update.

```
make -C /usr/lib/modules/6.4.3-arch1-1/build M=/var/lib/dkms/macbook12-spi-driver/0+git.314/build modules
  CC [M]  /var/lib/dkms/macbook12-spi-driver/0+git.314/build/applespi.o
  CC [M]  /var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ibridge.o
  CC [M]  /var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ib-tb.o
  CC [M]  /var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ib-als.o
/var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ib-tb.c: In function ‘appletb_fill_report_info’:
/var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ib-tb.c:949:9: warning: enumeration value ‘HID_REPORT_TYPES’ not handled in switch [-Wswitch]
  949 |         switch (field->report->type) {
      |         ^~~~~~
/var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ibridge.c:905:35: error: initialization of ‘void (*)(struct acpi_device *)’ from incompatible pointer type ‘int (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
  905 |                 .remove         = appleib_remove,
      |                                   ^~~~~~~~~~~~~~
/var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ibridge.c:905:35: note: (near initialization for ‘appleib_driver.ops.remove’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/macbook12-spi-driver/0+git.314/build/apple-ibridge.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:2026: /var/lib/dkms/macbook12-spi-driver/0+git.314/build] Error 2
make: *** [Makefile:16: all] Error 2
```

https://aur.archlinux.org/packages/macbook12-spi-driver-dkms

**Comment by LukeShortCloud** [comment]
I verified that the patch is being applied: https://aur.archlinux.org/cgit/aur.git/tree/linux-6.4.patch?h=macbook12-spi-driver-dkms

**Comment by LukeShortCloud** [comment]
This is no longer relevant since we switched to the t2linux kernel.

https://github.com/LukeShortCloud/winesapOS/issues/641
