### ISSUE TITLE
macbook12-spi-driver-dkms fails to install

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#584]
```
$ less /var/lib/dkms/macbook12-spi-driver/0+git.304/build/make.log
/var/lib/dkms/macbook12-spi-driver/0+git.304/build/applespi.c:1846.c:1846:15 error: implicit declaration of function "efivar_entry_set_safe" [-Werror=implicit-function-declaration]
```

This is most likely due to a new GCC version that sets this warning as an error by default now.

**Comment by LukeShortCloud** [comment]
There could be other issues from `linux-lts` being updated from Linux 5.10 to 6.1 recently in Arch Linux.

**Comment by LukeShortCloud** [comment]
This appears to be happening ever since the Linux 6.0 kernel. A workaround has been posted in a fork (a big thanks to @flavian112 for finding a workaround and @marc-git for putting this fork together!):

- https://github.com/roadrunner2/macbook12-spi-driver/issues/67#issuecomment-1315273486
- https://github.com/Dunedan/mbp-2016-linux/issues/189#issuecomment-1501535065
- https://github.com/marc-git/macbook12-spi-driver

**Comment by LukeShortCloud** [comment]
I reported this to the [macbook12-spi-driver-dkms AUR package](https://aur.archlinux.org/packages/macbook12-spi-driver-dkms#comment-917815) page in hopes that the patch can be added there.

**Comment by LukeShortCloud** [comment]
This issue has finally been fixed in the AUR package: https://aur.archlinux.org/cgit/aur.git/commit/?h=macbook12-spi-driver-dkms&id=4830cac0ea377a032fb104758c08098a17c56994

I can confirm that a new build with `linux-lts` (version 6.1.34-1-lts right now) works.

**Comment by devopswe** [comment]
> This issue has finally been fixed in the AUR package: https://aur.archlinux.org/cgit/aur.git/commit/?h=macbook12-spi-driver-dkms&id=4830cac0ea377a032fb104758c08098a17c56994
> 
> I can confirm that a new build with `linux-lts` (version 6.1.34-1-lts right now) works.

Can I use that package on my Fedora Linux distro ? or use only Arch distros ?

**Comment by LukeShortCloud** [comment]
Hey @devopswe , there is a package for it for Fedora but it is 2 years old and will not work.

You can follow the instructions for Debian here (ignore the outdated Fedora instructions below it). It should work on any Linux distribution, even.

https://github.com/marc-git/macbook12-spi-driver?tab=readme-ov-file#dkms-module-debian--co

If your system is fully-up-to-date, you'll need to apply the `linux-6.4.patch` patch for Linux >= 6.4 to work. Fedora is currently on 6.6.

https://aur.archlinux.org/cgit/aur.git/commit/?h=macbook12-spi-driver-dkms&id=fd2c2744b0524c8e27e9223288b80b2d000efa7c

As far as Macs go, I no longer have an Intel MacBook Pro to test with. I swapped it out for one with Apple Silicon. It used to work great with the Fedora Asahi Remix (as great as heavily work-in-progress driver support goes lol) until a recent macOS broke Asahi support entirely.

https://fedora-asahi-remix.org/

Good luck and have fun!
