### ISSUE TITLE
snd-hda-codec-cs8409 fails to compile

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#500]
```
+/workdir/scripts/winesapos-install.sh:867> chroot /winesapos sh -c $'git clone [https://github.com/egorenar/snd-hda-codec-cs8409.git;\n](https://github.com/egorenar/snd-hda-codec-cs8409.git;/n)  cd snd-hda-codec-cs8409;\n  export KVER=$(ls -1 /lib/modules/ | grep -P "^5.15");\n  make;\n  make install'
Cloning into 'snd-hda-codec-cs8409'...
make -C /lib/modules/5.15.76-1-lts/build CFLAGS_MODULE="-DAPPLE_PINSENSE_FIXUP -DAPPLE_CODECS -DCONFIG_SND_HDA_RECONFIG=1 -Wno-unused-variable -Wno-unused-function" M=/snd-hda-codec-cs8409 modules
make[1]: Entering directory '/usr/lib/modules/5.15.76-1-lts/build'
  CC [M]  /snd-hda-codec-cs8409/patch_cs8409.o
In file included from /snd-hda-codec-cs8409/patch_cs8409.c:16:
/snd-hda-codec-cs8409/patch_cs8409.h:15:10: fatal error: sound/cs42l42.h: No such file or directory
   15 | #include <sound/cs42l42.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:289: /snd-hda-codec-cs8409/patch_cs8409.o] Error 1
make[1]: *** [Makefile:1900: /snd-hda-codec-cs8409] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.15.76-1-lts/build'
make: *** [Makefile:16: all] Error 2
```

I have already found the issue to be that the git repository we clone has different branches based on the Linux kernel version it supports. We want to use the branch `linux5.14` which supports Linux 5.14 through 5.18 (we are using Linux LTS 5.15 currently).

We will need to switch to the `linux5.19` branch when we switch to the upcoming Linux LTS 6.1 kernel. Related: https://github.com/LukeShortCloud/winesapOS/issues/472

**Comment by LukeShortCloud** [comment]
On a related note, there is also an old sound driver repository `snd_hda_macbookpro` we no longer need. It only works on Linux 5.13 but we ship 5.13 (SteamOS Neptune kernel) and 5.15 (Linux upstream LTS). These two sound drivers conflict because they both provide the `snd-hda-cirrus` kernel driver. We will remove the old one as it is no longer needed.
